server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: ms-cliente

  datasource:
    url: jdbc:mysql://localhost:3306/ms_cliente?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

resilience4j.circuitbreaker:
  instances:
    categoriaListarPorIdCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
